services:
  prisma_postgres:
    image: postgres
    container_name: prisma_postgres
    restart: always
    ports:
      - 1234:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pg_app:/var/lib/postgresql/data

  app:
    container_name: node_app
    build: .
    ports:
      - 4000:4000
    depends_on:
      - prisma_postgres
    command: bash -c "npm run prod:migrate & npm run start"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - /usr/src/
  
volumes:
  pg_app: